import person1 from "@/assets/person1.jpg";
import person2 from "@/assets/person2.jpg";
import person3 from "@/assets/person3.jpg";
import person4 from "@/assets/person4.jpg";
import person5 from "@/assets/person5.jpg";
import person6 from "@/assets/person9.jpg";
import person7 from "@/assets/person7.jpg";
import person8 from "@/assets/person8.jpg";

export const providers = [
  {
    name: "Ravi Kumar",
    avatar: person5,
    service: "Certified Electrician • 7 years experience",
    rating: 4.9,
    reviews: 156,
    location: "Nashik",
    lat: 19.9975,
    lng: 73.7898,
    distance: 2.5,
    price: "₹400",
    verified: true,
    category: "electrician",
  },
  {
    name: "Amar Khan",
    avatar: person7,
    service: "Professional Plumber • 10 years experience",
    rating: 4.8,
    reviews: 132,
    location: "Mumbai",
    lat: 19.076,
    lng: 72.8777,
    distance: 1.2,
    price: "₹500",
    verified: true,
    category: "plumber",
  },
  {
    name: "Neha Sharma",
    avatar: person1,
    service: "Laundry & Ironing Expert • Same day delivery",
    rating: 4.7,
    reviews: 210,
    location: "Nagpur",
    lat: 21.1458,
    lng: 79.0882,
    distance: 0.8,
    price: "₹250",
    verified: true,
    category: "laundry",
  },
  {
    name: "Rohit Patel",
    avatar: person4,
    service: "Plumber • Pipe fixes & leakage sealing",
    rating: 4.9,
    reviews: 178,
    location: "Pune",
    lat: 18.5204,
    lng: 73.8567,
    distance: 3.2,
    price: "₹650",
    verified: true,
    category: "plumber",
  },
  {
    name: "Priya Nair",
    avatar: person2,
    service: "Cleaning Specialist • Deep cleaning expert",
    rating: 4.8,
    reviews: 240,
    location: "Mumbai",
    lat: 19.076,
    lng: 72.8777,
    distance: 2.0,
    price: "₹600",
    verified: true,
    category: "laundry",
  },
  {
    name: "Vikas Singh",
    avatar: person3,
    service: "Professional Electrician • Wire fixing",
    rating: 4.6,
    reviews: 189,
    location: "Nagpur",
    lat: 21.1458,
    lng: 79.0882,
    distance: 4.1,
    price: "₹550",
    verified: true,
    category: "electrician",
  },
  {
    name: "Anjali Gupta",
    avatar: person6,
    service: "Premium Laundry Service • Eco wash",
    rating: 4.7,
    reviews: 175,
    location: "Pune",
    lat: 18.5204,
    lng: 73.8567,
    distance: 1.6,
    price: "₹220",
    verified: true,
    category: "laundry",
  },
  {
    name: "Arjun Mehta",
    avatar: person8,
    service: "Plumber • Pipe fittings & maintenance",
    rating: 4.9,
    reviews: 120,
    location: "Nashik",
    lat: 19.9975,
    lng: 73.7898,
    distance: 0.9,
    price: "₹480",
    verified: true,
    category: "plumber",
  },
];
